# Generated by Django 6.0.2 on 2026-03-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='wallet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
