# Generated by Django 6.0.2 on 2026-03-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_user_notification_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='wallet',
            new_name='wallet_number',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
