# Generated by Django 6.0.2 on 2026-03-11 11:02

import django.db.models.deletion
import wallet.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_number', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('account_number', models.CharField(default=wallet.utils.generate_account_number, max_length=11, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'British Pound'), ('USD', 'US Dollar'), ('CHF', 'CHF'), ('JPY', 'Japanese Yen'), ('CAD', 'CAD'), ('NGN', 'Naira')], default='NGN', max_length=11)),
                ('status', models.CharField(choices=[('EUR', 'Euro'), ('GBP', 'British Pound'), ('USD', 'US Dollar'), ('CHF', 'CHF'), ('JPY', 'Japanese Yen'), ('CAD', 'CAD'), ('NGN', 'Naira')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.UUIDField(blank=True, editable=False, unique=True)),
                ('reciever_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='wallet.wallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], max_length=9)),
                ('reciever_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_receipts', to='wallet.wallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_receipts', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.wallet')),
            ],
        ),
    ]
