# Generated by Django 6.0.2 on 2026-03-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
