# Generated by Django 6.0.2 on 2026-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.BooleanField(choices=[('EUR', 'Euro'), ('GBP', 'British Pound'), ('USD', 'US Dollar'), ('CHF', 'CHF'), ('JPY', 'Japanese Yen'), ('CAD', 'CAD'), ('NGN', 'Naira')], default='ACTIVE', max_length=10),
        ),
    ]
